# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Beisi @ St. Jude
titleshort: Beisi
email: xubeisi#gmail.com
description: 
baseurl: ""
url: "https://xubeisi.github.io"

plugins:
  - jekyll-spaceship
  - jekyll-scholar
  - jemoji

sitemap:
  lastmod: 2021-01-01
  priority: 0.7
  changefreq: 'weekly'

jekyll-spaceship:
  processors:
    - table-processor

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

excerpt_separator: "<!--more-->"

scholar:
  last_name: Xu
  first_name: Beisi # bold for Group Lead
  first_names_team: Beisi
  style: apa
  locale: en
  sort_by: year,month
  order: descending,descending
  source: /_bibliography/
  bibliography: tm_beisi.bib
  bibliography_template: bib
  reference_tagname: div

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

devorprod: production

enable_google_analytics:    true
enable_google_tagmanager:   false

google_analytics:     G-7VM1P89105
google_tagmanager:    GTM-KBQBM37

max_width: 1200px
